version: '3.8'
services:
  mcsv-eureka-server:
    container_name: mcsv-eureka-server
    image: eureka-server:1.0.1
    # build:
    #   context: ./
    #   dockerfile: ./eureka-server/Dockerfile
    ports:
      - '8761:8761'
    networks:
      - spring
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.0'
    #       memory:  150M
    #     reservations:
    #       cpus: '0.5'
    #       memory: 100M

networks:
  spring:
    external: true
    name: spring
